name: manual run

on:
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner , year=2023 }}
          # getGithubUserContribution("mayureshzende", { year: 2023 })
          # getGithubUserContribution("platane", { from: 2023-12-01, to:2023-12-31 })
          outputs: |
            dist/only-svg/github-contribution-grid-snake.svg
            dist/only-svg/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: ensure the generated file exists
        run: |
          ls dist
          test -f dist/only-svg/github-contribution-grid-snake.svg
          test -f dist/only-svg/github-contribution-grid-snake-dark.svg

          test -f dist/docker/github-contribution-grid-snake.svg
          test -f dist/docker/github-contribution-grid-snake-dark.svg
          test -f dist/docker/github-contribution-grid-snake.gif

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: manual-run-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.NAME_GRAPH_TOKEN }}
